FROM node:10-alpine

# Prepare build
ARG ENV=docker
ARG BULLET_TRAIN_API_KEY=4vfqhypYjcPoGGu8ByrBaj
ARG BULLET_TRAIN_API_URL=https://api.bullet-train.restauranto.it/api/v1/
ARG BULLET_TRAIN_ASSET_URL=https://bullet-train.restauranto.it

# Create app directory
WORKDIR /usr/src/app

# Bundle app source
COPY . .

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

# Build the node application in prod mode
ENV ENV ${ENV}
ENV BULLET_TRAIN_API_KEY ${BULLET_TRAIN_API_KEY}
ENV BULLET_TRAIN_API_URL ${BULLET_TRAIN_API_URL}
ENV BULLET_TRAIN_ASSET_URL ${BULLET_TRAIN_ASSET_URL}

RUN npm i
RUN npm run env
RUN npm run bundle

EXPOSE 8080
CMD [ "npm", "run", "start" ]
